## Question 1

In [10]:
import hashlib
import os
path = "D:/test_data"
hashes = []
duplicate=[]
for (dir_path, dir_names, file_names) in os.walk(path):
    
    for filename in file_names:
        try:
            filepath = os.path.join(dir_path, filename)
            file = open(filepath, 'r')
            content = file.read().encode()
            file.close()
            message = hashlib.sha256(content)
            if message.hexdigest() not in hashes:
                hashes.append(message.hexdigest())
            else:
                
                duplicate.append(filename)
                os.remove(filepath)
        except Exception as e:
            print(e)
print(duplicate)

['file1.txt', 'file3.txt', 'file1.txt', 'file2.txt', 'file3.txt']


## Question 2

In [11]:
import random
import string
password = []
password.extend(random.choices(string.ascii_uppercase, k=1))
password.extend(random.choices(string.ascii_lowercase, k=2))
password.extend(random.choices('0123456789',k=3))
strongpassword = ""
random.shuffle(password)
for i in range(6):
    strongpassword += password[i]
print("Here is your password:", strongpassword)

Here is your password: 2wa60J


## Question 3

In [48]:
import numpy as np
def Prime(n):
    if(n<2):
        return False
    ctr=0
    for i in range(2,n//2+1):
        if(n<2):
            return False
        if(n%i==0):
            ctr+=1
    if(ctr==0 ):
        return True
    else:
        return False
r=int(input("Input number of rows"))
c=int(input("Input number of columns"))
req_arr=np.ones((r,c))
for i in range(r):
    for j in range(c):
        req_arr[i][j]=int(input())
x=0      
for i in range(r):
    for j in range(c):
        
        if(Prime(x)):
            req_arr[i][j]=int(req_arr[i][j]**3)
            x+=1
        else:
            x+=1
req_arr

Input number of rows3
Input number of columns3
1
2
3
4
5
6
7
8
9


array([[  1.,   2.,  27.],
       [ 64.,   5., 216.],
       [  7., 512.,   9.]])

## Question 4

In [51]:
new_arr=np.ones((r,c))
x=0
for i in range(r):
    for j in range(c):
        if(Prime(x)):
            print(req_arr[i][j])
            if(i-1<0):
                new_arr[i][j]=req_arr[i][j-1]+req_arr[i][j]
            elif(j-1<0):
                new_arr[i][j]=req_arr[i-1][j]+req_arr[i][j]
            else:
                new_arr[i][j]=data[i-1][j-1]+data[i][j]
            x+=1
        else:
            new_arr[i][j]=data[i][j]
            x+=1
new_arr

27.0
64.0
216.0
512.0


array([[  1.,   2.,  29.],
       [ 65.,   5., 218.],
       [  7., 576.,   9.]])

## Question 5

In [24]:
arr1=[1,2,3,4,5]
arr2=[2,3,5,7]
new_array=[]
for i in arr1:
    for j in arr2:
        if(i==j):
            new_array.append(i)
print(new_array)

[2, 3, 5]


## Question 6

In [17]:
import numpy as np

input_array=np.ones((7,7))
x=1
for i in range(7):
    for j in range(7):
        input_array[i][j]=input_array[i][j]*x*7
        x+=1
    

In [18]:
input_array

array([[  7.,  14.,  21.,  28.,  35.,  42.,  49.],
       [ 56.,  63.,  70.,  77.,  84.,  91.,  98.],
       [105., 112., 119., 126., 133., 140., 147.],
       [154., 161., 168., 175., 182., 189., 196.],
       [203., 210., 217., 224., 231., 238., 245.],
       [252., 259., 266., 273., 280., 287., 294.],
       [301., 308., 315., 322., 329., 336., 343.]])

## Question 7

In [53]:
arr3=np.ones((10,10),dtype='int8')
arr3[1::2,::2]=0
arr3[0::2,1::2]=0
arr3

array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]], dtype=int8)

## Question 8

In [57]:
arr_1 = ['A','B','C','D','E','F','G','H','I','a','K','L','M','N','o','P','Q','R','S','T','U','0','W','O']

ct=0
for i in range(0, len(arr_1)):
    if arr_1[i].lower() in 'aeiou':
        arr_1[i] = np.nan
        ct+=1
arr_1 = np.array(arr_1)
print(arr_1)
print(ct)


['nan' 'B' 'C' 'D' 'nan' 'F' 'G' 'H' 'nan' 'nan' 'K' 'L' 'M' 'N' 'nan' 'P'
 'Q' 'R' 'S' 'T' 'nan' '0' 'W' 'nan']
7
